# Generated by Django 5.2.2 on 2025-06-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverApp', '0002_historialoperacion_delete_solver'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialoperacion',
            name='datos_entrada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
