# Generated by Django 5.2.2 on 2025-06-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverApp', '0003_historialoperacion_datos_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialoperacion',
            name='expresion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
