# Generated by Django 5.2.2 on 2025-06-19 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverApp', '0004_alter_historialoperacion_expresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialoperacion',
            name='tabla',
            field=models.TextField(blank=True, null=True),
        ),
    ]
