# Generated by Django 5.2.2 on 2025-06-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverApp', '0006_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialoperacion',
            name='iteraciones',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialoperacion',
            name='pasos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
