# Generated by Django 5.2.2 on 2025-07-04 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solverApp', '0008_historialoperacion_grafica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMetodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('newton', 'Método de Newton-Raphson'), ('biseccion', 'Método de Bisección'), ('secante', 'Método de la Secante'), ('punto_fijo', 'Método de Punto Fijo'), ('integracion', 'Integración Numérica'), ('derivacion', 'Derivación Numérica')], max_length=50, unique=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('limite_iteraciones', models.IntegerField(default=100)),
                ('precision', models.FloatField(default=0.0001)),
                ('tiempo_maximo', models.IntegerField(default=30)),
                ('limite_uso_diario', models.IntegerField(default=50)),
                ('limite_uso_usuario', models.IntegerField(default=10)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Método',
                'verbose_name_plural': 'Configuraciones de Métodos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(default='SolverApp', max_length=100)),
                ('descripcion_sistema', models.TextField(default='Sistema de resolución de ecuaciones')),
                ('mantenimiento_activo', models.BooleanField(default=False)),
                ('mensaje_mantenimiento', models.TextField(default='El sistema está en mantenimiento. Intente más tarde.')),
                ('limite_operaciones_usuario', models.IntegerField(default=100)),
                ('limite_operaciones_dia', models.IntegerField(default=1000)),
                ('limite_tiempo_sesion', models.IntegerField(default=3600)),
                ('email_habilitado', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_usuario', models.CharField(blank=True, max_length=100)),
                ('smtp_password', models.CharField(blank=True, max_length=100)),
                ('smtp_tls', models.BooleanField(default=True)),
                ('notificaciones_admin', models.BooleanField(default=True)),
                ('notificaciones_usuario', models.BooleanField(default=True)),
                ('intentos_login_max', models.IntegerField(default=5)),
                ('tiempo_bloqueo_login', models.IntegerField(default=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
        migrations.CreateModel(
            name='LimiteUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('contador', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_uso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Límite de Uso',
                'verbose_name_plural': 'Límites de Uso',
                'unique_together': {('usuario', 'metodo', 'fecha')},
            },
        ),
    ]
